export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const GET_TODAY_DATA_REQUEST = "GET_TODAY_DATA_REQUEST";
export const GET_TODAY_DATA_SUCCESS = "GET_TODAY_DATA_SUCCESS";
export const GET_TODAY_DATA_FAILURE = "GET_TODAY_DATA_FAILURE";

export const GET_FILTERED_DATA_REQUEST = "GET_FILTERED_DATA_REQUEST";
export const GET_FILTERED_DATA_SUCCESS = "GET_FILTERED_DATA_SUCCESS";
export const GET_FILTERED_DATA_FAILURE = "GET_FILTERED_DATA_FAILURE";
